[project]
name = "extract-paradox-hive"
version = "1.0.3"
description = "Extract Paradox Anticheat custom properties from a Minecraft Bedrock save"
authors = [
    {name = "DJ Stomp",email = "85457381+DJStompZone@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "amulet-leveldb (>=1.0.7,<2.0.0)"
]
repository = "https://github.com/SeaMooLab/extract-paradox-hive"

[tool.poetry]
packages = [{include = "extract_paradox_hive"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
hive-extractor = "extract_paradox_hive.main:main"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "coverage (>=7.16.2,<8.0.0)",
    "pyflakes (>=4.0.3,<5.0.0)",
    "black (>=26.10.0,<27.0.0)",
    "pyright (>=1.1.414,<2.0.0)"
]
