"""
This type stub file was generated by pyright.
"""

from ._leveldb import Iterator, LevelDB, LevelDBEncrypted, LevelDBException, LevelDBIteratorException, repair_db
from . import _version

__version__ = ...
