"""
Type stub for amulet-leveldb's ``leveldb`` package.

Originally generated by pyright. Names are re-exported with the redundant
``as`` form (and listed in ``__all__``) because pyright treats a bare
``from x import y`` in a stub as private, which makes
``from leveldb import LevelDB`` fail with "unknown import symbol".
"""

from ._leveldb import Iterator as Iterator
from ._leveldb import LevelDB as LevelDB
from ._leveldb import LevelDBEncrypted as LevelDBEncrypted
from ._leveldb import LevelDBException as LevelDBException
from ._leveldb import LevelDBIteratorException as LevelDBIteratorException
from ._leveldb import repair_db as repair_db
from . import _version as _version

__version__: str

__all__ = [
    "Iterator",
    "LevelDB",
    "LevelDBEncrypted",
    "LevelDBException",
    "LevelDBIteratorException",
    "repair_db",
]
